language: python
python:
  - 2.7

###
### Add services
###
services:
  - docker


###
### Global variables
###
env:
  global:
    - MY_DOCKER_NAME="my-php-docker"
    - MY_VERSION="5.6"


###
### Install
###
install:

  # Show Docker version
  - docker version

  # Build my docker
  - docker build -t cytopia/${MY_DOCKER_NAME} .



###
### Test
###
script:

  ##
  ## 01.) [a](DEBUG) Test plain docker
  ##
  - docker run
      -e DEBUG_COMPOSE_ENTRYPOINT=1
      --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME} &
  - sleep 5
  - docker ps

  # Check version
  - docker exec ${MY_DOCKER_NAME} php --version | grep "PHP ${MY_VERSION}"
  # Check xdebug modules
  - docker exec ${MY_DOCKER_NAME} php -m | grep 'xdebug'
  # PHP-FPM is running?
  - docker exec ${MY_DOCKER_NAME} ps auxw | grep 'php-fpm'

  # Socat should not be running?
  - if docker exec ${MY_DOCKER_NAME} ps auxw | grep 'socat'; then false; else true; fi
  # No Custom Configuration (For this Round)
  - if docker exec ${MY_DOCKER_NAME} php --ini | grep -q 'custom.ini'; then && false; else true; fi
  # Check Timezone
  - docker exec ${MY_DOCKER_NAME} php -r "printf(\"%s\n\", ini_get('date.timezone'));" | grep 'UTC'

  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}"
  ##
  ## 01.) [b](SILENT) Test plain docker
  ##
  - docker run
      --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME} &
  - sleep 5
  - docker ps

  # Check version
  - docker exec ${MY_DOCKER_NAME} php --version | grep "PHP ${MY_VERSION}"
  # Check xdebug modules
  - docker exec ${MY_DOCKER_NAME} php -m | grep 'xdebug'
  # PHP-FPM is running?
  - docker exec ${MY_DOCKER_NAME} ps auxw | grep 'php-fpm'

  # Socat should not be running?
  - if docker exec ${MY_DOCKER_NAME} ps auxw | grep 'socat'; then false; else true; fi
  # No Custom Configuration (For this Round)
  - if docker exec ${MY_DOCKER_NAME} php --ini | grep -q 'custom.ini'; then && false; else true; fi
  # Check Timezone
  - docker exec ${MY_DOCKER_NAME} php -r "printf(\"%s\n\", ini_get('date.timezone'));" | grep 'UTC'

  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}"
